# Imagen base oficial de Bun
FROM oven/bun:1.1

# Carpeta de trabajo
WORKDIR /app

# Copiamos package.json y lockfile
COPY package.json bun.lockb* ./

# Instalamos dependencias
RUN bun install

# Copiamos el resto del código
COPY . .

# Generamos Prisma Client dentro del contenedor
RUN bunx prisma generate --schema=prisma/schema.prisma

# Exponemos el puerto de la API
EXPOSE 3000

# Comando por defecto
CMD ["bun", "run", "src/index.ts"]
